name: build-downstream-images-action

on:
  pull_request:
    branches:
      - '*-backports'
  push:
    branches:
    - '*-backports'

permissions:
  contents: read

jobs:
  build_CAPM3:
    runs-on: ubuntu-latest
    env:
      DEV_REGISTRY_ENDPOINT: registry.ci.mirantis.com
      PROD_REGISTRY_ENDPOINT: registry.mirantis.com
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        run: |
          git_tag=$(git describe --tags --abbrev=0)
          git_commit_hash=$(git rev-parse --short HEAD)
          git_version=$git_tag-$git_commit_hash
          echo "VERSION=$git_version" >> "$GITHUB_OUTPUT"
          echo "Using image version: $git_version"

      - name: Set target registry to dev
        if: github.event_name == 'pull_request'
        id: registry
        run: echo "REGISTRY=${{ env.DEV_REGISTRY_ENDPOINT }} >> "$GITHUB_OUTPUT"

      - name: Set target registry to prod
        if: github.event_name == 'push'
        id: registry
        run: echo "REGISTRY=${{ env.PROD_REGISTRY_ENDPOINT }} >> "$GITHUB_OUTPUT"

      - name: Docker login to dev MSR
        if: github.event_name == 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DEV_REGISTRY_ENDPOINT }}
          username: ${{ secrets.REGISTRY_CI_USERNAME }}
          password: ${{ secrets.REGISTRY_CI_PASSWORD }}

      - name: Docker login to prod MSR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.PROD_REGISTRY_ENDPOINT }}
          username: ${{ secrets.REGISTRY_PROD_USERNAME }}
          password: ${{ secrets.REGISTRY_PROD_PASSWORD }}

      - name: Build image
        shell: bash
        env:
          CONTROLLER_IMG: ${{ steps.registry.outputs.registry }}/k0rdent-bm/images/metal3-io/cluster-api-provider-metal3
          GOLANG_IMAGE: golang:1.23.6
          TAG: ${{ steps.version.outputs.version }}
        run: |
          docker run --rm -v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/cluster-api-provider-metal3:/go/src/github.com/metal3-io/cluster-api-provider-metal3 -w=/go/src/github.com/metal3-io/cluster-api-provider-metal3 ${GOLANG_IMAGE} make docker-build docker-push
